services:
  # backend:
  #   container_name: backend
  #   restart: always
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  
  # frontend:
  #   container_name: frontend
  #   restart: always
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:443

  postgresql:
    container_name: postgresql
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: battlequest
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    restart: always
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root

volumes:
  postgres_data: