name: ci

on:
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Set up Docekr Buildx
        uses: docker/setup-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/battlequest-backend:latest
      -
        name: Build and push Docker image
        run: |
          docker build -t backend .
          docker run -d --name battlequest-container backend
